language: php
php:
    - "5.4"

env:
    global:
         - secure: svI7A2V7c9E1GRnwYK60hvdHN8PCky2XTxlVG/sS5vpk65YuinTe6ppaco7aKS/ZJW6y3PNDMYV8tscYFro0GQ1hP2ai5gbIYhyUwP+eyMfLTZm0nfmB9pbj6B8vTjFNVPhOm/OBK+SLs06lSNrJsh16BHhXTSVsvnAZA1ioUolwD9nDm2OsGBwuzKtCP5MsywEUTlTWsEtBccgfi7p6o7VGJOeII/gQM9mWGacg1xZ/LpvyPoWg9tU4kWblN8v5++kOKeHEHuXMW6VEsuly6PhQP4cyoSMWZ7tS66c7cQQdXFcGPnkygilXmEr46EzdKZg1hjQYgM6OUB6vMqlapu3ZBDCLFCO5iyRvRzdbtmfQ00iuxIicPv8zZio963QIboo3sbE7ih2eI3JAlr1VwY7xus/vTiq//BmVgt69+xDG3b60WoEKW/rQWrmiYhoHSmBH6hjPPgAzb6f8LoBIuGWwUJsdyAsT740VghXoo89D/+nTJg+QT78taL/Me8+3uWxi+SucqE0kAAIjJ5F7n5ENnxu0Jh1QE2f5itAeIDzzQW3oVEYFTwy373ycQd9B7pGox7gVcpn+uNmVM3X13kLjTOSMr4hK5iCw46mlWYM8TrySkNYui55GjZ2CbSCV7YqU4zLdB6gMmY5OenJWxkPcervqiTacI7Vb4TrkZAE=
         - secure: i6seo3Vzb7mAUZO5jcPnBgsOhQCeX3J5F7NW8LLZ2Xsae6PQ8C0G601ez0loIsLOJx4TBQVV5lHh1+24w0bby/PQ5NGmP10DvRosKq+KvCa1SKmP5TQUt4l5ihkaipoT7mNQMFtaNG5zswKSd28hvSNewTOaZCNZ5aTb2dKELG8z4sgLGlkjAfpjMTSFrk1+fY/9tPF3jFynDUh4lh6SCXwJjpJyhlAsefNWsHHHJzA7j/tDHPTHNXzTLl6tAB9O7vLF65iuj7SAjugCPBoKpoNGY1rQE2r1eYjO589e7+0YuAmdJjLq0JmBlHKt+3HdHzSIWG6nNai/sTbSbvElRi+wz7COpwJtLIQdNCje8ZT0u2A1S5YT8IR8PWKI44Bmr5DWTe6xqAp+rNI2HMc1nrD69MCb1FFkA60UWI1QYWrEyc2fxM4fg/THMSV9haryUddAJLyPq+IK4lbE/lFJxYKqyHCV27/kiN+JWdMgi65hrj/ThrMXhs5OZDcDZYC7VhbZxP+xo4TTtWZ9SVvB+jcOkin0hmNW2+zVYM4BsrdOmxom8D5prZqaQUzAWuhlAIx2Q/QQSWMVcAy1F2WEF8RK+4JFoxugPdTTY+hNZ7xuewYPS2q9g/8lrLCN79ifPYOV30ar1KyYonnHaHuJ+Em6mc00nMIiW53L23/L23c=

         - secure: "CwbMjpjmTIEiQjVa1ACI1NT0AitPvTOS4sGcuL/ckxk+KVcZ3XS1sxvbGAibkb74KaNL+eWAutwCec4uVA2eOlc8G4ZoQjZ7/H3VCvgsJzWz6K3tswhqvf3oL8sZx7cqFiVeywYBYQJu33WakgOE+s4Lb7cI+OKyOXGhVAYeCswy3PW2kFGASEm6+WFHFqHdSJeunpmoTb14q17cdUDY3sjBRR8Sm9Ej3Cqbrz2Bo3UIrQqhSStmJ6m5b/X8Vwc/sXvMgJ8Mjvc3823etGQ9/oReKVNp0zlGT3y/AG6HmA30YT3YlS876v4xlUtsqPFHYKenhj0CtiS6+76jqbbmvzOT48M+JBf/7H9eRExrHJbUmgPEQBqZGctNKnk5KflZPGB1qpAxxxDLTpa0zoj9l5UyTfxMc6cUDMEEo1UBAPBQUcXMKMiZLMTAIjBFmUt7aa5sFHzQvRtL1Q0fyRq2ZH2g/eNn2p9RHKkcBgBw8s9Vcr6BrPWUnQMJaFDWZ5RG9PcgJGu4OZt0fqDIlIWTjazWzWhP+vC6hxRKqF1sAXjVTxxX4dTZ+Q2tBHitNvebmqeOl3rmIDKz6SqyBxcZeFatTURLI0X5AdEmhlpSDnMtmYHqBNPw79ME5OPBWPnAb7Hc9oSNFqx5qcOQZT/7kOpTPmOjWcOaWkCPDU/ZurA="
   
         - secure: "uYozEI5Y8IkZQ2FYnxFCVWj5qIVZ7kqX5MdK6nDotJlVLNy2sGx7s9S69lar+jw+C0g/2SkLWs2P+Of49SJtN/GCFvxAfKFHdLGQ0L1q5/zDelYTlNc6cucWHg3qZh8htF4Khc12MeTW18bIqcChKmSGhkwgCsAyc5PaXw4+H49Ssu1IezlgGkuo2j9mcBe1G4MYpBwvR3seI03T396Do11YJMzI171TO27vCwK3d9jA4hXyQpvR/fdey1jsUIaXOUPAZVDHI+c7P7NxiqEknntLUPqS89T581mWHXWl+pnuydFK56ydtL/FkJeHE0BlM+Os5IJqE6aCOK8iuQ5Vmq98z2K0OFRx8Go1nVLo9H6Dvha43PMvEr8T3L/SRz/jCAD6Twq8toJYjs3Mqi1XgPuPD7rke+ilhDgyFoGBfh+ZD3W/8UOhtTvBUPK6Kt2zcUm5t7ksJgvc5RGa8/KiDHzfAoBtlFQjk/FiSdUoasdXHNLTUsj2tcDIuCA0y9Upl358nBH5Rk+n7tlXT526OpiYjfHaTtZtUUcTffdYQ/H2ciG+vBch9LFVaaxVPBVx1LcfE21V9Y+0KgwjDwmowp0jmpHtWyMraEg05UIiYbx+e+1w9zeKUrzYpnPlzBoPXttrx797hvmEoZSSABOjUhEfvfuEk9+yQjSqg3H58os="

         - secure: "tqOBNoPTV+4yvtPfTdDohf0mNEBeYFodBu+cXJB5AUJ5tx/Ok3+6EP49fdm5lfoXOiIkVHzNlg8AcKAkH5tlZxqVrfAl4eatfBc2ymITr9XS3Oi9KxhIwEi09REUwLehHHnmHw+e2CoJGFTI4eevlQgTxM8f1fUnAPZEZ/aEgsiIcKxQG1g7yrL7qSqRRIbxfbYqnO1N3QZTF2EPYhWnbMu58GFxuX6CkdlbKnqoQ5N34UCvj6qMFs4HAR8imOKFRSM5o9PpwgdvbUB+/MHk1A947eKj13koQ8E/NRVmgtHid0kVAdM29gFk/WslcTfuuXlZMKhFYiOYXfF4vvdIhiZat7jXQOOHKxHEeaQkE6FwZj545wLtNuKg3NHooEetEigJhdcbdczL8w90UK6SUvy5S/cej65/zuo51vy60igRJaCHvIB1tz3+XCbcCF+tq0liFecE0C2/o3NjgNnYmR6PY6W8Ps7Q7QDADfWfmC85iy1BUJ4R90HYcTpasxc4Pd0CNOaa7ceZ7ecJJvZCIMhp9cUfXXyrmDpkwU7HfmbT8LV1SpkuTDPgFKPfYk/wSEzC9SHWWz5UOSSC4yXhVuOGfSn9+GuFUeDdbKuE1SmgEpPJeqpCXE+7UOz63UYKknjXVibIT4MBs+NckLKDs6N42hZ9f+mzEWsoBMgsYjU="

         - secure: "OhJGJYcskZJ+bkKSHgbCbsrjOHXDg14pNksAnx0ZnA0ol6E8LwvMLqF++S1sjy6baDfGmYGeVemeug08vjgA1Z+VgTmEr7rr1+l6tTve+1bDuNKumvQkhhHpCz6XTaZ/m2o0R3xzib4UBBavhk/PXZ/mK4HBGJmZMcExAtIzL1hv4+pgXCpLbSail/JvxCItJ1JhuSiGj5Ucti6vxNUI5rLfFF1o6sl4/TaME/td3VhAlVsSaNcX/Opf7fJvFbjcvUoAQ1jFiIB9dTKNRwhWMFYtX5V2qez3SDOkadfDtp/vCrQd9O/f35PYX5aHOMJUCQByDBgdgz2AupqNsGjCnMjdSqh3jDRy+UTC/R8XskJSPAv/6flbt15M+8QceWDhKELyid5FuTdi8rPw3RtX+an/TEIxwjIDRLOmlXIpIaLwdX6ryqGtH4wgDs33kncm7sP6+uA8wC8LquWcZ7GWyIKoNFLxmva5SwfwvBBHwj7Zf7n/9H3/x1l03gD9E6V3Y4FWmq6zoKf695bgpR0ZmR6nq65nlqnpJzJuXOAjTHQTfWDzlf6N5rNBiHTK1HoHzqLhlkhwSeE3VrsazrXvHxzVJJXiMOdS1OZ4ckDW2hhTQzNyNVICvUzFD2yFmRK6dFwlhKivsZAJL3ud20YOA7y0MM74A0w4B3APgB2RpK0="

         - CORE_BRANCH=stable8


addons:
  sauce_connect: true

before_install:
    - sudo apt-get update
    - sudo apt-get install apache2 libapache2-mod-fastcgi curl
    - bash travis-build/install_oc.sh $CORE_BRANCH
    # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # configure apache virtual hosts
    - sudo cp -f travis-build/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    - sleep 3
    - chmod +x core/occ
    - ./core/occ app:disable firstrunwizard
install: 
    - mv travis-build/config.py.travis config.py
    - cd sauce
    - sudo pip install -r sauce_requirements.txt

script: ./run_sauce_tests.sh
