language: php
python:
    - "5.4"

env:
    - CORE_BRANCH=stable8


before_install:
    - sudo apt-get update
    - sudo pip install requests unittest-data-provider
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    - bash travis-build/install_oc.sh $CORE_BRANCH
    # enable php-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    # configure apache virtual hosts
    - sudo cp -f travis-build/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install: 
    - "sudo pip install -r requirements.txt"
    - mv travis-build/config.py.travis config.py

script: python runtests.py
